### ISSUE TITLE
Sphinx >= 1.5a1 doesn't work

### ISSUE THREAD

**Issue by myint** [myint/rstcheck#18]
I've disabled this version of Sphinx in 541d3554de99568ff6bc82c45bcb02bea9b0766f.

```
$ ./test_rstcheck.py
F..FF.FF.FF..FFFF...
======================================================================
FAIL: test_check (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 59, in test_check
    """))
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
6

======================================================================
FAIL: test_check_doctest_in_code_block (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 329, in test_check_doctest_in_code_block
    """))
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
7
Items in the second set but not the first:
4

======================================================================
FAIL: test_check_doctest_in_python_code_block (__main__.Tests)
I'm not sure if this is correct, but I've seen people do it.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 345, in test_check_doctest_in_python_code_block
    """))
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
7
...
```

https://travis-ci.org/myint/rstcheck/builds/166606676

This is related to #8.

**Comment by myint** [comment]
This is because importing `sphinx` no longer has the side effect of registering roles and directives (https://github.com/sphinx-doc/sphinx/issues/2799).
