### ISSUE TITLE
Unit test errors on PyPy3

### ISSUE THREAD

**Issue by jayvdb** [myint/rstcheck#29]
PyPy3 2.6 and PyPy3-3.3 both have unit test errors.

```
$ ./test_rstcheck.py
........FF.F..........s...

======================================================================
FAIL: test_check_json (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 78, in test_check_json
    """\
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
7

Items in the second set but not the first:
5

======================================================================
FAIL: test_check_json_with_bad_ignore (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 127, in test_check_json_with_bad_ignore
    """\
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
7

Items in the second set but not the first:
5

======================================================================
FAIL: test_check_json_with_unmatched_ignores_only (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_rstcheck.py", line 110, in test_check_json_with_unmatched_ignores_only
    """\
  File "./test_rstcheck.py", line 19, in assert_lines_equal
    self.assertEqual(set(line_numbers), set(dict(results)))
AssertionError: Items in the first set but not the second:
7

Items in the second set but not the first:
5

----------------------------------------------------------------------
Ran 26 tests in 0.706s

FAILED (failures=3, skipped=1)
```
https://travis-ci.org/jayvdb/rstcheck/builds/213974625

**Comment by myint** [comment]
It looks like its `json` module just doesn't support reporting line numbers.

```
$ ~/Downloads/pypy3-v5.5.0-osx64/bin/pypy3 foo.py
Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    json.loads("""
  File "/Users/myint/Downloads/pypy3-v5.5.0-osx64/lib-python/3/json/__init__.py", line 322, in loads
    return _pypyjson.loads(s) if _pypyjson else _default_decoder.decode(s)
ValueError: Unexpected ':' when decoding array (char 12)
```

```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    """)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 10 (char 12)
```

**Comment by myint** [comment]
PyPy 3 seems to be fixed now. I guess the solution was just to wait. 😄

```
$ pypy3 --version
Python 3.5.3 (d72f9800a42b46a8056951b1da2426d2c2d8d502, Oct 06 2017, 10:36:43)
[PyPy 5.9.0-beta0 with GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
$ pypy3 foo.py
Traceback (most recent call last):
  File "foo.py", line 2, in <module>
    json.loads("""
  File "/opt/local/lib/pypy3/lib-python/3/json/__init__.py", line 326, in loads
    if _pypyjson else _default_decoder.decode(s))
json.decoder.JSONDecodeError: Unexpected ':' when decoding array: line 3 column 10 (char 12)
```

```
$ pypy3 test_rstcheck.py
......................s...
----------------------------------------------------------------------
Ran 26 tests in 0.643s

OK (skipped=1)
```
