### ISSUE TITLE
`..math::` causes crash

### ISSUE THREAD

**Issue by ojgc** [myint/rstcheck#71]
test.rst

```
.. math::

  HALF = \frac{1}{2}

====
Test
===
```

Produces no output and returns 0.  Running rstcheck with --debug gives:
```
Traceback (most recent call last):
  File "/bin/rstcheck", line 11, in <module>
    sys.exit(main())
  File "/lib/python2.7/site-packages/rstcheck.py", line 950, in main
    results = [_check_file((args.files[0], args))]
  File "/lib/python2.7/site-packages/rstcheck.py", line 277, in _check_file
    debug=args.debug):
  File "/lib/python2.7/site-packages/rstcheck.py", line 189, in check
    'warning_stream': string_io})
  File "/lib/python2.7/site-packages/docutils/core.py", line 417, in publish_string
    enable_exit_status=enable_exit_status)
  File "/lib/python2.7/site-packages/docutils/core.py", line 665, in publish_programmatically
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "/lib/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/lib/python2.7/site-packages/docutils/readers/__init__.py", line 71, in read
    self.parse()
  File "/lib/python2.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/lib/python2.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/lib/python2.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/directives/patches.py", line 127, in run
    docname=self.state.document.settings.env.docname,
AttributeError: Values instance has no attribute 'env'
```

**Comment by Cielquan** [comment]
I cannot reproduce this issue with python 3.8.10 and rstcheck 4.0.0.

**Comment by Cielquan** [comment]
I just saw in the stack trace that you use python 2.7 which is got deprecated with rstcheck 3.5 and dropped in 4.0.
